services:
  - type: web
    name: gymchope-test-deployment
    env: ruby
    buildCommand: bundle install && yarn install
    startCommand: bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: DATABASE_URL
        value:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: 1
      - key: WEB_CONCURRENCY
        value: 1
    disk:
      - name: render-disk
        mountPath: /var/lib/postgresql/data
        sizeGB: 10